---
apiVersion: v1
kind: ConfigMap
metadata:
  name: villains-config
  namespace: superheroes
data:
  db.database: "villains_database"
  db.password: "badman"
  db.username: "badman"
  quarkus.datasource.jdbc.url: "jdbc:postgresql://villains-database:5432/villains_database"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villains-database
  namespace: superheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: villains-database
  template:
    metadata:
      labels:
        name: villains-database
      namespace: superheroes
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              valueFrom:
                configMapKeyRef:
                  key: db.username
                  name: villains-config
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db.password
                  name: villains-config
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db.database
                  name: villains-config
          image: centos/postgresql-96-centos7
          imagePullPolicy: IfNotPresent
          name: villains-database
          ports:
            - containerPort: 5432
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: villains-database
  namespace: superheroes
spec:
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: villains-database
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 48dea8b094d630499489d61a5dd86fc8c54b3660
    app.quarkus.io/build-timestamp: 2023-03-30 - 08:20:11 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: rest-villains
  name: rest-villains
  namespace: superheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: rest-villains
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 48dea8b094d630499489d61a5dd86fc8c54b3660
        app.quarkus.io/build-timestamp: 2023-03-30 - 08:20:11 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: rest-villains
      namespace: superheroes
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: quarkus.datasource.jdbc.url
              valueFrom:
                configMapKeyRef:
                  key: quarkus.datasource.jdbc.url
                  name: villains-config
            - name: quarkus.datasource.username
              valueFrom:
                configMapKeyRef:
                  key: db.username
                  name: villains-config
            - name: quarkus.datasource.password
              valueFrom:
                configMapKeyRef:
                  key: db.password
                  name: villains-config
          image: jeremygilbert/rest-villains:1.0.0
          imagePullPolicy: IfNotPresent
          name: rest-villains
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
      serviceAccountName: rest-villains
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 48dea8b094d630499489d61a5dd86fc8c54b3660
    app.quarkus.io/build-timestamp: 2023-03-30 - 08:20:11 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: rest-villains
  name: rest-villains
  namespace: superheroes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rest-villains-view
  namespace: superheroes
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: rest-villains
    namespace: superheroes
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 48dea8b094d630499489d61a5dd86fc8c54b3660
    app.quarkus.io/build-timestamp: 2023-03-30 - 08:20:11 +0000
  labels:
    app.kubernetes.io/name: rest-villains
    app.kubernetes.io/version: 1.0.0
  name: rest-villains
  namespace: superheroes
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: rest-villains
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
