apiVersion: v1
data:
  POSTGRESQL_HOST: "villains-database"
  POSTGRESQL_USER: "badman"
  POSTGRESQL_PASSWORD: "badman"
  POSTGRESQL_DATABASE: "villains_database"
kind: ConfigMap
metadata:
  name: villains-config
  namespace: superheroes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villains-database
  namespace: superheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: villains-database
  template:
    metadata:
      labels:
        name: villains-database
    spec:
      containers:
        - name: villains-database
          image: centos/postgresql-96-centos7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
              name: http
          envFrom:
            - configMapRef:
                name: villains-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: superheroes
  name: villains-database
spec:
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: villains-database
  type: ClusterIP
