apiVersion: v1
data:
  postgresql-host: "villains-database"
  postgresql-user: "badman"
  postgresql-password: "badman"
  postgresql-database: "villains_database"
kind: ConfigMap
metadata:
  name: villains-config
  namespace: superheroes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villains-database
  namespace: superheroes
spec:
  replicas: 1
  selector:
    matchLabels:
      name: villains-database
  template:
    metadata:
      labels:
        name: villains-database
    spec:
      containers:
        - name: villains-database
          image: centos/postgresql-96-centos7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
              name: http
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                configMapKeyRef:
                  key: postgresql-user
                  name: villains-config
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: postgresql-password
                  name: villains-config
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: postgresql-database
                  name: villains-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: superheroes
  name: villains-database
spec:
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: villains-database
  type: ClusterIP
