apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rest-statistic
  namespace: superheroes
spec:
  ingressClassName: nginx
  rules:
    - host: superheroes.com
      http:
        paths:
          - backend:
              service:
                name: rest-statistic
                port:
                  number: 80
            path: /
            pathType: Prefix